export const MEALTICKT_FILTER_TYPE = {
  AVAILABLE: 'AVAILABLE',
  UNAVAILABLE: 'UNAVAILABLE',
} as const;

export const CATEGORY_FILTER_TYPE = {
  KOREAN: 'KOREAN',
  FASTFOOD: 'FASTFOOD',
  WESTERN: 'WESTERN',
  JAPANESE: 'JAPANESE',
  CAFE: 'CAFE',
} as const;